### ISSUE TITLE
Make any improvement you think is suitable

### ISSUE THREAD

**Issue by fabianaboldrin** [fabianaboldrin/web-crawler#2]
you can make any improvement in the code or in the documentation to make it better. Feel free, any help is welcome.

**Comment by pBouillon** [comment]
I'll see what I can do !

**Comment by nikhilkumarsingh** [comment]
Check out #7

**Comment by DivisionMax** [comment]
Silly question but how do I get access rights to push a branch and create a PR? I implemented logging over `print` statements (generally better practice) and implemented consistent use of the new the string formatting method (curly braces, `{}`) over the old `%s` style.

**Comment by fabianaboldrin** [comment]
First of all, you need to fork my repo. When you do it, you'll have access to make any change you want. After that you'll commit this changes into your master branch and create a new PR. 
Hope i've helped
